"""remove unique constraint from username

Revision ID: 424074120d98
Revises: 38b764a32e45
Create Date: 2026-10-02 21:01:00.089142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424074120d98'
down_revision: Union[str, Sequence[str], None] = '38b764a32e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profiles_username_key', 'profiles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('profiles_username_key', 'profiles', ['username'])
    # ### end Alembic commands ###
