"""Add transcription config and summary status

Revision ID: f5cba9c1fc94
Revises: 
Create Date: 2026-10-02 04:53:25.958871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5cba9c1fc94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_notes', sa.Column('transcription_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audio_notes', sa.Column('resolved_language', sa.Text(), nullable=True))
    op.add_column('audio_notes', sa.Column('summary_status', sa.Text(), server_default='not_requested', nullable=False))
    op.add_column('audio_notes', sa.Column('summary_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('audio_notes', sa.Column('summary_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('audio_notes', 'status',
               existing_type=postgresql.ENUM('created', 'uploading', 'uploaded', 'queued', 'transcribing', 'summarizing', 'completed', 'failed', name='audio_status'),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'created'::audio_status"),
               postgresql_using='status::text')
    op.add_column('transcript_segments', sa.Column('speaker_id', sa.Integer(), nullable=True))
    op.add_column('transcript_segments', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('transcript_segments', sa.Column('language_detected', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript_segments', 'language_detected')
    op.drop_column('transcript_segments', 'confidence')
    op.drop_column('transcript_segments', 'speaker_id')
    op.alter_column('audio_notes', 'status',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('created', 'uploading', 'uploaded', 'queued', 'transcribing', 'summarizing', 'completed', 'failed', name='audio_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'created'::audio_status"),
               postgresql_using='status::audio_status')
    op.drop_column('audio_notes', 'summary_completed_at')
    op.drop_column('audio_notes', 'summary_requested_at')
    op.drop_column('audio_notes', 'summary_status')
    op.drop_column('audio_notes', 'resolved_language')
    op.drop_column('audio_notes', 'transcription_config')
    # ### end Alembic commands ###
